### ISSUE TITLE
Any suggestions how to get the bot to trigger stuff when a outside event happens?

### ISSUE THREAD

**Issue by theqa-ninja** [FreedomBen/slackbot_frd#3]
Looking for a way to trigger the bot to do certain events when a condition is met.  Here's what I thought I could do.

a) have the bot constantly query an api to see if it returns true.
b) make something to listen for an API call coming in
c) set up some frankstein project for api where when the e-mail comes in, I'd post in a private slack channel and slackbot would see it :)

Any suggestions?

Example: when someone emails in a specific e-mail subject, I'd like to get the slackbot to post in the channel.

Thanks!

**Comment by FreedomBen** [comment]
I think you'll need a solution that's dependent on the event itself.  For email, I think I'd look at setting up Amazon SES with a lambda that auto-triggers from it.  Then have that lambda function hit the slack API (probably chat.postMessage).

If it's something you can poll, you could just have a ruby script that `require 'slackbot_frd` and then does it's thing and posts when necessary.  It can be called from a cron job.  There's a small example here:  https://github.com/FreedomBen/slackbot_frd#directly-calling-slack-methods

I used this in the past for grabbing upcoming calendar events and posting them to slack, as well as standup reminders

**Comment by theqa-ninja** [comment]
Thanks!
